import { useEffect, useRef } from "react";
import Head from "next/head";
import Mysection from "../components/Mysection";
import styles from "../styles/Home.module.scss";
import BulletNavigation from "../components/BulletNav";

export default function Home() {
  const section1 = useRef(null);
  const section2 = useRef(null);
  const section3 = useRef(null);
  const section4 = useRef(null);
  const section5 = useRef(null);
  function scrollTo(section) {
    section.current.scrollIntoView({ behavior: "smooth" });
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BulletNavigation
        sectionRefs={[section1, section2, section3, section4, section5]}
      />

      <div className={`container ${styles.container}`}>
        <div ref={section1} className="active" id="first">
          <Mysection
            image={`/images/6.png`}
            title={`A kinetic revolution`}
            headline={`powered sustainably by seaweed biofuel`}
            goToSectionRef={section2}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={section2} id="second">
          <Mysection
            image={`/images/t4.png`}
            title={`Science meets science fition`}
            headline={`250,000km on A single fuel cell charge`}
            goToSectionRef={section3}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={section3} id="third">
          <Mysection
            image={`/images/3.png`}
            title={`Comfortable and luxurious design`}
            headline={`Materials derived from ocean plastics`}
            goToSectionRef={section4}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={section4} id="fourth">
          <Mysection
            image={`/images/2.png`}
            title={`Choose nori, moss, or sea grapes`}
            headline={`a masterpiece of innovation and elegance`}
            goToSectionRef={section5}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={section5} id="fifth">
          <Mysection
            image={`/images/t1.png`}
            title={`from the ocean, for the ocean`}
            headline={`an Amphibious vehicle for the ocean’s future`}
            goToSectionRef={section1}
            scrollTo={scrollTo}
            showArrow={false}
          />
        </div>
      </div>
    </div>
  );
}
